generator:
  class: sfDoctrineGenerator
  param:
    model_class:           email_directory
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          email_directory
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [id, directory_key, title, send_to_list]
      filter:
        display: [directory_key, title, created_at, updated_at]
      form:    ~
      edit:    ~
      new:     ~
