generator:
  class: sfDoctrineGenerator
  param:
    model_class:           member
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          member
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: Members
        display: [ first_name, last_name, email_address, country, is_active, created_at]
        object_actions:
          _edit: ~
        batch_actions: []
        actions: []
        sort: [created_at, desc]
      filter:  
        display: [ first_name, last_name, email_address, country, is_active ]
      form:    
        display:
            Personal: [ first_name, middle_name, last_name, email_address, dob, gender, married, marriage_anniversary  ]
            Account: [ is_active, password, password_again,  _account ]
            NR Address: [ nri_address ]
            India Address: [ in_address ]
            Contact: [ nri_mobile, nri_landline, nri_office, nri_fax ]
            India Contact: [ in_landline, in_mobile ]
            Occupation: [ occupation_type, job_title, industry, other_income_source, passport_no, pan_no ]
            Family: [ family0, family1, family2, family3, family4 ]
        fields:
          email_address: 
            attributes:
              size: 80
      edit:    
        title: Edit Member "%%first_name%% %%last_name%%"
        actions:
          _save: ~
          _list: ~
      new:     ~
