## YAML Template.
#indexSuccess:
  #javascripts: 
  #  - -jquery-1.9.0.min.js
  #  - -jquery-ui-1.10.0.custom/js/jquery-ui-1.10.0.custom.min.js
  
listSuccess:
  javascripts: 
    - -jquery-1.9.0.min.js
    - -jquery-ui-1.10.0.custom/js/jquery-ui-1.10.0.custom.min.js
activateMemberSuccess:
  stylesheets: [ ui-lightness/jquery-ui-1.10.0.custom.min.css]
      