<?php

/**
 * Baseblog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $title
 * @property integer $author_id
 * @property text $summary
 * @property text $blog
 * @property varchar $image
 * @property integer $status
 * @property boolean $alert_on_comment
 * @property boolean $approved
 * @property Doctrine_Collection $blog_tag
 * @property Doctrine_Collection $blog_comment
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method varchar             getTitle()            Returns the current record's "title" value
 * @method integer             getAuthorId()         Returns the current record's "author_id" value
 * @method text                getSummary()          Returns the current record's "summary" value
 * @method text                getBlog()             Returns the current record's "blog" value
 * @method varchar             getImage()            Returns the current record's "image" value
 * @method integer             getStatus()           Returns the current record's "status" value
 * @method boolean             getAlertOnComment()   Returns the current record's "alert_on_comment" value
 * @method boolean             getApproved()         Returns the current record's "approved" value
 * @method Doctrine_Collection getBlogTag()          Returns the current record's "blog_tag" collection
 * @method Doctrine_Collection getBlogComment()      Returns the current record's "blog_comment" collection
 * @method blog                setId()               Sets the current record's "id" value
 * @method blog                setTitle()            Sets the current record's "title" value
 * @method blog                setAuthorId()         Sets the current record's "author_id" value
 * @method blog                setSummary()          Sets the current record's "summary" value
 * @method blog                setBlog()             Sets the current record's "blog" value
 * @method blog                setImage()            Sets the current record's "image" value
 * @method blog                setStatus()           Sets the current record's "status" value
 * @method blog                setAlertOnComment()   Sets the current record's "alert_on_comment" value
 * @method blog                setApproved()         Sets the current record's "approved" value
 * @method blog                setBlogTag()          Sets the current record's "blog_tag" collection
 * @method blog                setBlogComment()      Sets the current record's "blog_comment" collection
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseblog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('blog');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'size' => 8,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('title', 'varchar', 300, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 300,
             ));
        $this->hasColumn('author_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('summary', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
        $this->hasColumn('blog', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
        $this->hasColumn('image', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'size' => 1,
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('alert_on_comment', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('approved', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('blog_tag', array(
             'local' => 'id',
             'foreign' => 'blog_id'));

        $this->hasMany('blog_comment', array(
             'local' => 'id',
             'foreign' => 'blog_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             'unique' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}