<?php

/**
 * Basetag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $tag
 * @property Doctrine_Collection $blog_tag
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method string              getTag()      Returns the current record's "tag" value
 * @method Doctrine_Collection getBlogTag()  Returns the current record's "blog_tag" collection
 * @method tag                 setId()       Sets the current record's "id" value
 * @method tag                 setTag()      Sets the current record's "tag" value
 * @method tag                 setBlogTag()  Sets the current record's "blog_tag" collection
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basetag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tag');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'size' => 4,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('tag', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('blog_tag', array(
             'local' => 'id',
             'foreign' => 'tag_id'));
    }
}