<?php

/**
 * Baseitr_other_income
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $submission_id
 * @property integer $category_id
 * @property string $details
 * @property date $date_rcvd
 * @property decimal $amount
 * @property itr_submission $itr_submission
 * 
 * @method integer          getId()             Returns the current record's "id" value
 * @method integer          getSubmissionId()   Returns the current record's "submission_id" value
 * @method integer          getCategoryId()     Returns the current record's "category_id" value
 * @method string           getDetails()        Returns the current record's "details" value
 * @method date             getDateRcvd()       Returns the current record's "date_rcvd" value
 * @method decimal          getAmount()         Returns the current record's "amount" value
 * @method itr_submission   getItrSubmission()  Returns the current record's "itr_submission" value
 * @method itr_other_income setId()             Sets the current record's "id" value
 * @method itr_other_income setSubmissionId()   Sets the current record's "submission_id" value
 * @method itr_other_income setCategoryId()     Sets the current record's "category_id" value
 * @method itr_other_income setDetails()        Sets the current record's "details" value
 * @method itr_other_income setDateRcvd()       Sets the current record's "date_rcvd" value
 * @method itr_other_income setAmount()         Sets the current record's "amount" value
 * @method itr_other_income setItrSubmission()  Sets the current record's "itr_submission" value
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseitr_other_income extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('itr_other_income');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('submission_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             ));
        $this->hasColumn('category_id', 'integer', 1, array(
             'type' => 'integer',
             'size' => 1,
             'notnull' => false,
             'length' => 1,
             ));
        $this->hasColumn('details', 'string', 300, array(
             'type' => 'string',
             'size' => 300,
             'notnull' => false,
             'length' => 300,
             ));
        $this->hasColumn('date_rcvd', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('amount', 'decimal', 19, array(
             'type' => 'decimal',
             'size' => 19,
             'scale' => 2,
             'notnull' => false,
             'length' => 19,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('itr_submission', array(
             'local' => 'submission_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}