<?php

/**
 * Basesubscription
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $code
 * @property string $name
 * @property date $start_date
 * @property date $end_date
 * @property string $currency
 * @property decimal $price
 * @property boolean $disabled
 * @property string $template
 * @property Doctrine_Collection $subscription_product
 * @property Doctrine_Collection $member_subscription
 * 
 * @method integer             getId()                   Returns the current record's "id" value
 * @method string              getCode()                 Returns the current record's "code" value
 * @method string              getName()                 Returns the current record's "name" value
 * @method date                getStartDate()            Returns the current record's "start_date" value
 * @method date                getEndDate()              Returns the current record's "end_date" value
 * @method string              getCurrency()             Returns the current record's "currency" value
 * @method decimal             getPrice()                Returns the current record's "price" value
 * @method boolean             getDisabled()             Returns the current record's "disabled" value
 * @method string              getTemplate()             Returns the current record's "template" value
 * @method Doctrine_Collection getSubscriptionProduct()  Returns the current record's "subscription_product" collection
 * @method Doctrine_Collection getMemberSubscription()   Returns the current record's "member_subscription" collection
 * @method subscription        setId()                   Sets the current record's "id" value
 * @method subscription        setCode()                 Sets the current record's "code" value
 * @method subscription        setName()                 Sets the current record's "name" value
 * @method subscription        setStartDate()            Sets the current record's "start_date" value
 * @method subscription        setEndDate()              Sets the current record's "end_date" value
 * @method subscription        setCurrency()             Sets the current record's "currency" value
 * @method subscription        setPrice()                Sets the current record's "price" value
 * @method subscription        setDisabled()             Sets the current record's "disabled" value
 * @method subscription        setTemplate()             Sets the current record's "template" value
 * @method subscription        setSubscriptionProduct()  Sets the current record's "subscription_product" collection
 * @method subscription        setMemberSubscription()   Sets the current record's "member_subscription" collection
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basesubscription extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('subscription');
        $this->hasColumn('id', 'integer', 5, array(
             'type' => 'integer',
             'size' => 5,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 5,
             ));
        $this->hasColumn('code', 'string', 20, array(
             'type' => 'string',
             'size' => 20,
             'notnull' => true,
             'unique' => true,
             'length' => 20,
             ));
        $this->hasColumn('name', 'string', 200, array(
             'type' => 'string',
             'size' => 200,
             'notnull' => false,
             'length' => 200,
             ));
        $this->hasColumn('start_date', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('end_date', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('currency', 'string', 3, array(
             'type' => 'string',
             'size' => 3,
             'notnull' => false,
             'length' => 3,
             ));
        $this->hasColumn('price', 'decimal', 18, array(
             'type' => 'decimal',
             'size' => 18,
             'scale' => 2,
             'notnull' => false,
             'length' => 18,
             ));
        $this->hasColumn('disabled', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             ));
        $this->hasColumn('template', 'string', 60, array(
             'type' => 'string',
             'size' => 60,
             'notnull' => false,
             'length' => 60,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('subscription_product', array(
             'local' => 'id',
             'foreign' => 'subscription_id'));

        $this->hasMany('member_subscription', array(
             'local' => 'id',
             'foreign' => 'subscription_id'));
    }
}