<?php

/**
 * Baseemail_directory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $directory_key
 * @property string $title
 * @property string $send_to
 * @property string $email_subject
 * @property string $email_templates
 * @property boolean $is_html
 * 
 * @method integer         getId()              Returns the current record's "id" value
 * @method string          getDirectoryKey()    Returns the current record's "directory_key" value
 * @method string          getTitle()           Returns the current record's "title" value
 * @method string          getSendTo()          Returns the current record's "send_to" value
 * @method string          getEmailSubject()    Returns the current record's "email_subject" value
 * @method string          getEmailTemplates()  Returns the current record's "email_templates" value
 * @method boolean         getIsHtml()          Returns the current record's "is_html" value
 * @method email_directory setId()              Sets the current record's "id" value
 * @method email_directory setDirectoryKey()    Sets the current record's "directory_key" value
 * @method email_directory setTitle()           Sets the current record's "title" value
 * @method email_directory setSendTo()          Sets the current record's "send_to" value
 * @method email_directory setEmailSubject()    Sets the current record's "email_subject" value
 * @method email_directory setEmailTemplates()  Sets the current record's "email_templates" value
 * @method email_directory setIsHtml()          Sets the current record's "is_html" value
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseemail_directory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('email_directory');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'size' => 8,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('directory_key', 'string', 255, array(
             'type' => 'string',
             'size' => 255,
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'size' => 255,
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('send_to', 'string', 4000, array(
             'type' => 'string',
             'size' => 4000,
             'notnull' => false,
             'length' => 4000,
             ));
        $this->hasColumn('email_subject', 'string', 255, array(
             'type' => 'string',
             'size' => 255,
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('email_templates', 'string', 4000, array(
             'type' => 'string',
             'size' => 4000,
             'notnull' => false,
             'length' => 4000,
             ));
        $this->hasColumn('is_html', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}
