<?php

/**
 * Baseitr_property
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $submission_id
 * @property string $address
 * @property string $locality
 * @property string $city
 * @property string $state
 * @property string $pin
 * @property boolean $co_owned
 * @property string $percent_share
 * @property string $owners
 * @property boolean $let_out
 * @property string $tenant
 * @property string $tenant_pan
 * @property decimal $rent_not_realized
 * @property decimal $tax_paid
 * @property boolean $loan_taken
 * @property decimal $property_cost
 * @property decimal $loan_amount
 * @property decimal $loan_repaid
 * @property decimal $interest_paid
 * @property decimal $loan_oustanding
 * @property string $prev_year_receipt
 * @property decimal $rent_rcvd
 * @property string $rent_details
 * @property itr_submission $itr_submission
 * 
 * @method integer        getId()                Returns the current record's "id" value
 * @method integer        getSubmissionId()      Returns the current record's "submission_id" value
 * @method string         getAddress()           Returns the current record's "address" value
 * @method string         getLocality()          Returns the current record's "locality" value
 * @method string         getCity()              Returns the current record's "city" value
 * @method string         getState()             Returns the current record's "state" value
 * @method string         getPin()               Returns the current record's "pin" value
 * @method boolean        getCoOwned()           Returns the current record's "co_owned" value
 * @method string         getPercentShare()      Returns the current record's "percent_share" value
 * @method string         getOwners()            Returns the current record's "owners" value
 * @method boolean        getLetOut()            Returns the current record's "let_out" value
 * @method string         getTenant()            Returns the current record's "tenant" value
 * @method string         getTenantPan()         Returns the current record's "tenant_pan" value
 * @method decimal        getRentNotRealized()   Returns the current record's "rent_not_realized" value
 * @method decimal        getTaxPaid()           Returns the current record's "tax_paid" value
 * @method boolean        getLoanTaken()         Returns the current record's "loan_taken" value
 * @method decimal        getPropertyCost()      Returns the current record's "property_cost" value
 * @method decimal        getLoanAmount()        Returns the current record's "loan_amount" value
 * @method decimal        getLoanRepaid()        Returns the current record's "loan_repaid" value
 * @method decimal        getInterestPaid()      Returns the current record's "interest_paid" value
 * @method decimal        getLoanOustanding()    Returns the current record's "loan_oustanding" value
 * @method string         getPrevYearReceipt()   Returns the current record's "prev_year_receipt" value
 * @method decimal        getRentRcvd()          Returns the current record's "rent_rcvd" value
 * @method string         getRentDetails()       Returns the current record's "rent_details" value
 * @method itr_submission getItrSubmission()     Returns the current record's "itr_submission" value
 * @method itr_property   setId()                Sets the current record's "id" value
 * @method itr_property   setSubmissionId()      Sets the current record's "submission_id" value
 * @method itr_property   setAddress()           Sets the current record's "address" value
 * @method itr_property   setLocality()          Sets the current record's "locality" value
 * @method itr_property   setCity()              Sets the current record's "city" value
 * @method itr_property   setState()             Sets the current record's "state" value
 * @method itr_property   setPin()               Sets the current record's "pin" value
 * @method itr_property   setCoOwned()           Sets the current record's "co_owned" value
 * @method itr_property   setPercentShare()      Sets the current record's "percent_share" value
 * @method itr_property   setOwners()            Sets the current record's "owners" value
 * @method itr_property   setLetOut()            Sets the current record's "let_out" value
 * @method itr_property   setTenant()            Sets the current record's "tenant" value
 * @method itr_property   setTenantPan()         Sets the current record's "tenant_pan" value
 * @method itr_property   setRentNotRealized()   Sets the current record's "rent_not_realized" value
 * @method itr_property   setTaxPaid()           Sets the current record's "tax_paid" value
 * @method itr_property   setLoanTaken()         Sets the current record's "loan_taken" value
 * @method itr_property   setPropertyCost()      Sets the current record's "property_cost" value
 * @method itr_property   setLoanAmount()        Sets the current record's "loan_amount" value
 * @method itr_property   setLoanRepaid()        Sets the current record's "loan_repaid" value
 * @method itr_property   setInterestPaid()      Sets the current record's "interest_paid" value
 * @method itr_property   setLoanOustanding()    Sets the current record's "loan_oustanding" value
 * @method itr_property   setPrevYearReceipt()   Sets the current record's "prev_year_receipt" value
 * @method itr_property   setRentRcvd()          Sets the current record's "rent_rcvd" value
 * @method itr_property   setRentDetails()       Sets the current record's "rent_details" value
 * @method itr_property   setItrSubmission()     Sets the current record's "itr_submission" value
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseitr_property extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('itr_property');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('submission_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             ));
        $this->hasColumn('address', 'string', 500, array(
             'type' => 'string',
             'size' => 500,
             'notnull' => false,
             'length' => 500,
             ));
        $this->hasColumn('locality', 'string', 150, array(
             'type' => 'string',
             'size' => 150,
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('city', 'string', 70, array(
             'type' => 'string',
             'size' => 70,
             'notnull' => false,
             'length' => 70,
             ));
        $this->hasColumn('state', 'string', 10, array(
             'type' => 'string',
             'size' => 10,
             'notnull' => false,
             'length' => 10,
             ));
        $this->hasColumn('pin', 'string', 10, array(
             'type' => 'string',
             'size' => 10,
             'notnull' => false,
             'length' => 10,
             ));
        $this->hasColumn('co_owned', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             ));
        $this->hasColumn('percent_share', 'string', 10, array(
             'type' => 'string',
             'size' => 10,
             'notnull' => false,
             'length' => 10,
             ));
        $this->hasColumn('owners', 'string', 600, array(
             'type' => 'string',
             'size' => 600,
             'notnull' => false,
             'length' => 600,
             ));
        $this->hasColumn('let_out', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             ));
        $this->hasColumn('tenant', 'string', 100, array(
             'type' => 'string',
             'size' => 100,
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('tenant_pan', 'string', 12, array(
             'type' => 'string',
             'size' => 12,
             'notnull' => false,
             'length' => 12,
             ));
        $this->hasColumn('rent_not_realized', 'decimal', 19, array(
             'type' => 'decimal',
             'size' => 19,
             'scale' => 2,
             'notnull' => false,
             'length' => 19,
             ));
        $this->hasColumn('tax_paid', 'decimal', 19, array(
             'type' => 'decimal',
             'size' => 19,
             'scale' => 2,
             'notnull' => false,
             'length' => 19,
             ));
        $this->hasColumn('loan_taken', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             ));
        $this->hasColumn('property_cost', 'decimal', 19, array(
             'type' => 'decimal',
             'size' => 19,
             'scale' => 2,
             'notnull' => false,
             'length' => 19,
             ));
        $this->hasColumn('loan_amount', 'decimal', 19, array(
             'type' => 'decimal',
             'size' => 19,
             'scale' => 2,
             'notnull' => false,
             'length' => 19,
             ));
        $this->hasColumn('loan_repaid', 'decimal', 19, array(
             'type' => 'decimal',
             'size' => 19,
             'scale' => 2,
             'notnull' => false,
             'length' => 19,
             ));
        $this->hasColumn('interest_paid', 'decimal', 19, array(
             'type' => 'decimal',
             'size' => 19,
             'scale' => 2,
             'notnull' => false,
             'length' => 19,
             ));
        $this->hasColumn('loan_oustanding', 'decimal', 19, array(
             'type' => 'decimal',
             'size' => 19,
             'scale' => 2,
             'notnull' => false,
             'length' => 19,
             ));
        $this->hasColumn('prev_year_receipt', 'string', 600, array(
             'type' => 'string',
             'size' => 600,
             'length' => 600,
             ));
        $this->hasColumn('rent_rcvd', 'decimal', 19, array(
             'type' => 'decimal',
             'size' => 19,
             'scale' => 2,
             'notnull' => false,
             'length' => 19,
             ));
        $this->hasColumn('rent_details', 'string', 600, array(
             'type' => 'string',
             'size' => 600,
             'notnull' => false,
             'length' => 600,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('itr_submission', array(
             'local' => 'submission_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}