<?php

/**
 * Basesettings
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $setting_key
 * @property varchar $value1
 * @property varchar $value2
 * @property varchar $value3
 * @property text $description
 * 
 * @method varchar  getSettingKey()  Returns the current record's "setting_key" value
 * @method varchar  getValue1()      Returns the current record's "value1" value
 * @method varchar  getValue2()      Returns the current record's "value2" value
 * @method varchar  getValue3()      Returns the current record's "value3" value
 * @method text     getDescription() Returns the current record's "description" value
 * @method settings setSettingKey()  Sets the current record's "setting_key" value
 * @method settings setValue1()      Sets the current record's "value1" value
 * @method settings setValue2()      Sets the current record's "value2" value
 * @method settings setValue3()      Sets the current record's "value3" value
 * @method settings setDescription() Sets the current record's "description" value
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basesettings extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('settings');
        $this->hasColumn('setting_key', 'varchar', 255, array(
             'type' => 'varchar',
             'unique' => true,
             'primary' => true,
             'length' => 255,
             ));
        $this->hasColumn('value1', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('value2', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('value3', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('description', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}