<?php

/**
 * Baseproduct_category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $product
 * 
 * @method Doctrine_Collection getProduct() Returns the current record's "product" collection
 * @method product_category    setProduct() Sets the current record's "product" collection
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseproduct_category extends type_info
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('product', array(
             'local' => 'id',
             'foreign' => 'category_id'));
    }
}