<?php

/**
 * Basecoupon
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property integer $coupon_type
 * @property integer $discount_type
 * @property decimal $discount_rate
 * @property integer $limit_per_member
 * @property integer $quantity
 * @property boolean $active
 * @property Doctrine_Collection $member_coupon
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method string              getTitle()            Returns the current record's "title" value
 * @method integer             getCouponType()       Returns the current record's "coupon_type" value
 * @method integer             getDiscountType()     Returns the current record's "discount_type" value
 * @method decimal             getDiscountRate()     Returns the current record's "discount_rate" value
 * @method integer             getLimitPerMember()   Returns the current record's "limit_per_member" value
 * @method integer             getQuantity()         Returns the current record's "quantity" value
 * @method boolean             getActive()           Returns the current record's "active" value
 * @method Doctrine_Collection getMemberCoupon()     Returns the current record's "member_coupon" collection
 * @method coupon              setId()               Sets the current record's "id" value
 * @method coupon              setTitle()            Sets the current record's "title" value
 * @method coupon              setCouponType()       Sets the current record's "coupon_type" value
 * @method coupon              setDiscountType()     Sets the current record's "discount_type" value
 * @method coupon              setDiscountRate()     Sets the current record's "discount_rate" value
 * @method coupon              setLimitPerMember()   Sets the current record's "limit_per_member" value
 * @method coupon              setQuantity()         Sets the current record's "quantity" value
 * @method coupon              setActive()           Sets the current record's "active" value
 * @method coupon              setMemberCoupon()     Sets the current record's "member_coupon" collection
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecoupon extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('coupon');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'size' => 8,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'size' => 255,
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('coupon_type', 'integer', 2, array(
             'type' => 'integer',
             'size' => 2,
             'notnull' => false,
             'length' => 2,
             ));
        $this->hasColumn('discount_type', 'integer', 1, array(
             'type' => 'integer',
             'size' => 1,
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('discount_rate', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 2,
             'notnull' => false,
             ));
        $this->hasColumn('limit_per_member', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             ));
        $this->hasColumn('quantity', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             ));
        $this->hasColumn('active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('member_coupon', array(
             'local' => 'id',
             'foreign' => 'coupon_id'));
    }
}