<?php

/**
 * Basenewsnevent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property boolean $is_event
 * @property date $event_date
 * @property string $picture_file
 * @property string $title
 * @property string $subtitle
 * @property string $event_body
 * @property boolean $disabled
 * 
 * @method integer    getId()           Returns the current record's "id" value
 * @method boolean    getIsEvent()      Returns the current record's "is_event" value
 * @method date       getEventDate()    Returns the current record's "event_date" value
 * @method string     getPictureFile()  Returns the current record's "picture_file" value
 * @method string     getTitle()        Returns the current record's "title" value
 * @method string     getSubtitle()     Returns the current record's "subtitle" value
 * @method string     getEventBody()    Returns the current record's "event_body" value
 * @method boolean    getDisabled()     Returns the current record's "disabled" value
 * @method newsnevent setId()           Sets the current record's "id" value
 * @method newsnevent setIsEvent()      Sets the current record's "is_event" value
 * @method newsnevent setEventDate()    Sets the current record's "event_date" value
 * @method newsnevent setPictureFile()  Sets the current record's "picture_file" value
 * @method newsnevent setTitle()        Sets the current record's "title" value
 * @method newsnevent setSubtitle()     Sets the current record's "subtitle" value
 * @method newsnevent setEventBody()    Sets the current record's "event_body" value
 * @method newsnevent setDisabled()     Sets the current record's "disabled" value
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basenewsnevent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('newsnevent');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('is_event', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             ));
        $this->hasColumn('event_date', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('picture_file', 'string', 255, array(
             'type' => 'string',
             'size' => 255,
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'size' => 255,
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('subtitle', 'string', 255, array(
             'type' => 'string',
             'size' => 255,
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('event_body', 'string', 1000, array(
             'type' => 'string',
             'size' => 1000,
             'notnull' => false,
             'length' => 1000,
             ));
        $this->hasColumn('disabled', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}