<?php

/**
 * Baseticket_file
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $comment_id
 * @property varchar $file_name
 * @property varchar $original_name
 * @property ticket_comment $ticket_comment
 * 
 * @method integer        getId()             Returns the current record's "id" value
 * @method integer        getCommentId()      Returns the current record's "comment_id" value
 * @method varchar        getFileName()       Returns the current record's "file_name" value
 * @method varchar        getOriginalName()   Returns the current record's "original_name" value
 * @method ticket_comment getTicketComment()  Returns the current record's "ticket_comment" value
 * @method ticket_file    setId()             Sets the current record's "id" value
 * @method ticket_file    setCommentId()      Sets the current record's "comment_id" value
 * @method ticket_file    setFileName()       Sets the current record's "file_name" value
 * @method ticket_file    setOriginalName()   Sets the current record's "original_name" value
 * @method ticket_file    setTicketComment()  Sets the current record's "ticket_comment" value
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseticket_file extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ticket_file');
        $this->hasColumn('id', 'integer', 5, array(
             'type' => 'integer',
             'size' => 5,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 5,
             ));
        $this->hasColumn('comment_id', 'integer', 5, array(
             'type' => 'integer',
             'size' => 5,
             'notnull' => true,
             'unsigned' => true,
             'length' => 5,
             ));
        $this->hasColumn('file_name', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('original_name', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => false,
             'length' => 255,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ticket_comment', array(
             'local' => 'comment_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}