<?php

/**
 * Basecart
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $member_id
 * @property integer $status
 * @property integer $ip_address
 * @property member $member
 * @property Doctrine_Collection $cart_items
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method integer             getMemberId()   Returns the current record's "member_id" value
 * @method integer             getStatus()     Returns the current record's "status" value
 * @method integer             getIpAddress()  Returns the current record's "ip_address" value
 * @method member              getMember()     Returns the current record's "member" value
 * @method Doctrine_Collection getCartItems()  Returns the current record's "cart_items" collection
 * @method cart                setId()         Sets the current record's "id" value
 * @method cart                setMemberId()   Sets the current record's "member_id" value
 * @method cart                setStatus()     Sets the current record's "status" value
 * @method cart                setIpAddress()  Sets the current record's "ip_address" value
 * @method cart                setMember()     Sets the current record's "member" value
 * @method cart                setCartItems()  Sets the current record's "cart_items" collection
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecart extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cart');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('member_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('status', 'integer', 2, array(
             'type' => 'integer',
             'size' => 2,
             'notnull' => false,
             'length' => 2,
             ));
        $this->hasColumn('ip_address', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('member', array(
             'local' => 'member_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('cart_items', array(
             'local' => 'id',
             'foreign' => 'cart_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}