<?php

/**
 * Basepan_application
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basepan_application extends submission
{
    public function setUp()
    {
        parent::setUp();
        
    }
}