<?php

/**
 * Basesetting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $setting_key
 * @property varchar $description
 * @property varchar $value1
 * @property varchar $value2
 * @property varchar $value3
 * 
 * @method integer getId()          Returns the current record's "id" value
 * @method varchar getSettingKey()  Returns the current record's "setting_key" value
 * @method varchar getDescription() Returns the current record's "description" value
 * @method varchar getValue1()      Returns the current record's "value1" value
 * @method varchar getValue2()      Returns the current record's "value2" value
 * @method varchar getValue3()      Returns the current record's "value3" value
 * @method setting setId()          Sets the current record's "id" value
 * @method setting setSettingKey()  Sets the current record's "setting_key" value
 * @method setting setDescription() Sets the current record's "description" value
 * @method setting setValue1()      Sets the current record's "value1" value
 * @method setting setValue2()      Sets the current record's "value2" value
 * @method setting setValue3()      Sets the current record's "value3" value
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basesetting extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('setting');
        $this->hasColumn('id', 'integer', 2, array(
             'type' => 'integer',
             'size' => 2,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 2,
             ));
        $this->hasColumn('setting_key', 'varchar', 40, array(
             'type' => 'varchar',
             'notnull' => true,
             'unique' => true,
             'length' => 40,
             ));
        $this->hasColumn('description', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('value1', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('value2', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('value3', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}