<?php

/**
 * Basedepartment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $support_ticket
 * 
 * @method Doctrine_Collection getSupportTicket()  Returns the current record's "support_ticket" collection
 * @method department          setSupportTicket()  Sets the current record's "support_ticket" collection
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basedepartment extends type_info
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('support_ticket', array(
             'local' => 'id',
             'foreign' => 'department_id'));
    }
}