<?php

/**
 * Baseitr_file
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $submission_id
 * @property integer $category_id
 * @property string $filename
 * @property itr_submission $itr_submission
 * 
 * @method integer        getId()             Returns the current record's "id" value
 * @method integer        getSubmissionId()   Returns the current record's "submission_id" value
 * @method integer        getCategoryId()     Returns the current record's "category_id" value
 * @method string         getFilename()       Returns the current record's "filename" value
 * @method itr_submission getItrSubmission()  Returns the current record's "itr_submission" value
 * @method itr_file       setId()             Sets the current record's "id" value
 * @method itr_file       setSubmissionId()   Sets the current record's "submission_id" value
 * @method itr_file       setCategoryId()     Sets the current record's "category_id" value
 * @method itr_file       setFilename()       Sets the current record's "filename" value
 * @method itr_file       setItrSubmission()  Sets the current record's "itr_submission" value
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseitr_file extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('itr_file');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('submission_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             ));
        $this->hasColumn('category_id', 'integer', 2, array(
             'type' => 'integer',
             'size' => 2,
             'unsigned' => true,
             'length' => 2,
             ));
        $this->hasColumn('filename', 'string', 255, array(
             'type' => 'string',
             'size' => 255,
             'notnull' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('itr_submission', array(
             'local' => 'submission_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}