<?php

/**
 * Basefaq
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $question
 * @property string $answer
 * @property integer $ordering
 * @property boolean $active
 * 
 * @method varchar getQuestion() Returns the current record's "question" value
 * @method string  getAnswer()   Returns the current record's "answer" value
 * @method integer getOrdering() Returns the current record's "ordering" value
 * @method boolean getActive()   Returns the current record's "active" value
 * @method faq     setQuestion() Sets the current record's "question" value
 * @method faq     setAnswer()   Sets the current record's "answer" value
 * @method faq     setOrdering() Sets the current record's "ordering" value
 * @method faq     setActive()   Sets the current record's "active" value
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basefaq extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('faq');
        $this->hasColumn('question', 'varchar', 250, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 250,
             ));
        $this->hasColumn('answer', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('ordering', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 2,
             ));
        $this->hasColumn('active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'question',
             ),
             ));
        $this->actAs($sluggable0);
    }
}