<?php

/**
 * Baseorder_item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $order_id
 * @property integer $product_id
 * @property integer $quantity
 * @property decimal $price
 * @property order $order
 * @property product $product
 * 
 * @method integer    getId()         Returns the current record's "id" value
 * @method integer    getOrderId()    Returns the current record's "order_id" value
 * @method integer    getProductId()  Returns the current record's "product_id" value
 * @method integer    getQuantity()   Returns the current record's "quantity" value
 * @method decimal    getPrice()      Returns the current record's "price" value
 * @method order      getOrder()      Returns the current record's "order" value
 * @method product    getProduct()    Returns the current record's "product" value
 * @method order_item setId()         Sets the current record's "id" value
 * @method order_item setOrderId()    Sets the current record's "order_id" value
 * @method order_item setProductId()  Sets the current record's "product_id" value
 * @method order_item setQuantity()   Sets the current record's "quantity" value
 * @method order_item setPrice()      Sets the current record's "price" value
 * @method order_item setOrder()      Sets the current record's "order" value
 * @method order_item setProduct()    Sets the current record's "product" value
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseorder_item extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('order_item');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('order_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             'unsigned' => true,
             ));
        $this->hasColumn('product_id', 'integer', 5, array(
             'type' => 'integer',
             'size' => 5,
             'notnull' => false,
             'unsigned' => true,
             'length' => 5,
             ));
        $this->hasColumn('quantity', 'integer', 2, array(
             'type' => 'integer',
             'size' => 2,
             'notnull' => false,
             'length' => 2,
             ));
        $this->hasColumn('price', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('order', array(
             'local' => 'order_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}