<?php

/**
 * Baseaddress
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $address_type
 * @property integer $member_id
 * @property varchar $flat_no
 * @property varchar $premises
 * @property varchar $street
 * @property varchar $area
 * @property varchar $city
 * @property varchar $state
 * @property varchar $country
 * @property varchar $pin
 * @property member $member
 * 
 * @method integer getId()           Returns the current record's "id" value
 * @method integer getAddressType()  Returns the current record's "address_type" value
 * @method integer getMemberId()     Returns the current record's "member_id" value
 * @method varchar getFlatNo()       Returns the current record's "flat_no" value
 * @method varchar getPremises()     Returns the current record's "premises" value
 * @method varchar getStreet()       Returns the current record's "street" value
 * @method varchar getArea()         Returns the current record's "area" value
 * @method varchar getCity()         Returns the current record's "city" value
 * @method varchar getState()        Returns the current record's "state" value
 * @method varchar getCountry()      Returns the current record's "country" value
 * @method varchar getPin()          Returns the current record's "pin" value
 * @method member  getMember()       Returns the current record's "member" value
 * @method address setId()           Sets the current record's "id" value
 * @method address setAddressType()  Sets the current record's "address_type" value
 * @method address setMemberId()     Sets the current record's "member_id" value
 * @method address setFlatNo()       Sets the current record's "flat_no" value
 * @method address setPremises()     Sets the current record's "premises" value
 * @method address setStreet()       Sets the current record's "street" value
 * @method address setArea()         Sets the current record's "area" value
 * @method address setCity()         Sets the current record's "city" value
 * @method address setState()        Sets the current record's "state" value
 * @method address setCountry()      Sets the current record's "country" value
 * @method address setPin()          Sets the current record's "pin" value
 * @method address setMember()       Sets the current record's "member" value
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseaddress extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('address');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'size' => 4,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('address_type', 'integer', 2, array(
             'type' => 'integer',
             'size' => 2,
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('member_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('flat_no', 'varchar', 255, array(
             'type' => 'varchar',
             'size' => 255,
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('premises', 'varchar', 255, array(
             'type' => 'varchar',
             'size' => 255,
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('street', 'varchar', 255, array(
             'type' => 'varchar',
             'size' => 255,
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('area', 'varchar', 255, array(
             'type' => 'varchar',
             'size' => 255,
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('city', 'varchar', 255, array(
             'type' => 'varchar',
             'size' => 255,
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('state', 'varchar', 20, array(
             'type' => 'varchar',
             'size' => 20,
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('country', 'varchar', 20, array(
             'type' => 'varchar',
             'size' => 20,
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('pin', 'varchar', 20, array(
             'type' => 'varchar',
             'size' => 20,
             'notnull' => false,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('member', array(
             'local' => 'member_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}