<?php

/**
 * Basecontact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $contact_type
 * @property integer $member_id
 * @property varchar $country
 * @property varchar $isd_code
 * @property varchar $std_code
 * @property varchar $contact_text
 * @property varchar $first_name
 * @property varchar $last_name
 * @property date $dob
 * @property integer $relation
 * @property member $member
 * 
 * @method integer getId()           Returns the current record's "id" value
 * @method integer getContactType()  Returns the current record's "contact_type" value
 * @method integer getMemberId()     Returns the current record's "member_id" value
 * @method varchar getCountry()      Returns the current record's "country" value
 * @method varchar getIsdCode()      Returns the current record's "isd_code" value
 * @method varchar getStdCode()      Returns the current record's "std_code" value
 * @method varchar getContactText()  Returns the current record's "contact_text" value
 * @method varchar getFirstName()    Returns the current record's "first_name" value
 * @method varchar getLastName()     Returns the current record's "last_name" value
 * @method date    getDob()          Returns the current record's "dob" value
 * @method integer getRelation()     Returns the current record's "relation" value
 * @method member  getMember()       Returns the current record's "member" value
 * @method contact setId()           Sets the current record's "id" value
 * @method contact setContactType()  Sets the current record's "contact_type" value
 * @method contact setMemberId()     Sets the current record's "member_id" value
 * @method contact setCountry()      Sets the current record's "country" value
 * @method contact setIsdCode()      Sets the current record's "isd_code" value
 * @method contact setStdCode()      Sets the current record's "std_code" value
 * @method contact setContactText()  Sets the current record's "contact_text" value
 * @method contact setFirstName()    Sets the current record's "first_name" value
 * @method contact setLastName()     Sets the current record's "last_name" value
 * @method contact setDob()          Sets the current record's "dob" value
 * @method contact setRelation()     Sets the current record's "relation" value
 * @method contact setMember()       Sets the current record's "member" value
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecontact extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contact');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'size' => 4,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('contact_type', 'integer', 2, array(
             'type' => 'integer',
             'size' => 2,
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('member_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('country', 'varchar', 20, array(
             'type' => 'varchar',
             'size' => 20,
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('isd_code', 'varchar', 10, array(
             'type' => 'varchar',
             'size' => 10,
             'notnull' => false,
             'length' => 10,
             ));
        $this->hasColumn('std_code', 'varchar', 10, array(
             'type' => 'varchar',
             'size' => 10,
             'notnull' => false,
             'length' => 10,
             ));
        $this->hasColumn('contact_text', 'varchar', 150, array(
             'type' => 'varchar',
             'size' => 150,
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('first_name', 'varchar', 255, array(
             'type' => 'varchar',
             'size' => 255,
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'varchar', 255, array(
             'type' => 'varchar',
             'size' => 255,
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('dob', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('relation', 'integer', 2, array(
             'type' => 'integer',
             'size' => 2,
             'notnull' => false,
             'length' => 2,
             ));

        $this->setSubClasses(array(
             'family_contact' => 
             array(
              'contact_type' => 6,
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('member', array(
             'local' => 'member_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}