default:
  http_metas:
    content-type: text/html

  metas:
    title:         Groworth NRI Services - Admin
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [backend/main.css, dcmegamenu.css, skins/blue.css ]

  javascripts:    [jquery-1.9.0.min.js, jquery-ui-1.10.0.custom/js/jquery-ui-1.10.0.custom.min.js, jquery.hoverIntent.minified.js, jquery.dcmegamenu.1.3.3.min.js ]

  has_layout:     true
  layout:         layout
