<?php

/**
 * addressTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class addressTable extends Doctrine_Table
{
    const ADDRESS_TYPE_NRI = 1;
    const ADDRESS_TYPE_IND = 2;
    /**
     * Returns an instance of this class.
     *
     * @return object addressTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('address');
    }
}