<?php

/**
 * billing_unitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class billing_unitTable extends type_infoTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object billing_unitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('billing_unit');
    }
}