<?php

/**
 * blog_commentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class blog_commentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object blog_commentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('blog_comment');
    }
}