<?php

/**
 * blog_tagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class blog_tagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object blog_tagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('blog_tag');
    }
}