<?php

/**
 * blogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class blogTable extends Doctrine_Table
{
    const STATUS_DRAFT = 1;
    const STATUS_PUBLISHED = 2;
    
    static $status_choices = array
    (
        self::STATUS_DRAFT=>"Draft",
        self::STATUS_PUBLISHED=>"Published (Subject to Approval)",
    );
    
    /**
     * Returns an instance of this class.
     *
     * @return object blogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('blog');
    }
}