<?php

/**
 * cartTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class cartTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object cartTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('cart');
    }
}