<?php

/**
 * cart_itemsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class cart_itemsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object cart_itemsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('cart_items');
    }
}