<?php

/**
 * contactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class contactTable extends Doctrine_Table
{
    const CONTACT_TYPE_MOBILE = 1;
    const CONTACT_TYPE_LANDLINE = 2;
    const CONTACT_TYPE_OFFICE = 3;
    const CONTACT_TYPE_FAX = 4;
    const CONTACT_TYPE_EMAIL = 5;
    const CONTACT_TYPE_FAMILY = 6;
    
    /**
     * Returns an instance of this class.
     *
     * @return object contactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('contact');
    }
}