<?php

/**
 * countryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class countryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object countryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('country');
    }
}