<?php

/**
 * couponTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class couponTable extends Doctrine_Table
{
    const COUPON_TYPE_SPOUCE_DISCOUNT = 1;
    const COUPON_TYPE_BACK_YEAR_ITR   = 2;
    /**
     * Returns an instance of this class.
     *
     * @return object couponTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('coupon');
    }
}