<?php

/**
 * departmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class departmentTable extends type_infoTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object departmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('department');
    }
}