<?php

/**
 * email_directory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class email_directory extends Baseemail_directory
{
  public function getSendToList() {
    $return = "";
    $send_to = unserialize($this->getSendTo());
    foreach($send_to as $k => $v)
    {
      //$return = $v['name']."". $v['email'];
      if(trim($v['name']) != "" || trim($v['email']) != "")
        $return .= sprintf("Name: %s, Email: %s \n", $v['name'], $v['email']);
    }
    return $return;
  }
}