<?php

/**
 * email_directoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class email_directoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object email_directoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('email_directory');
    }
}