<?php

/**
 * exemption_categoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class exemption_categoryTable extends type_infoTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object exemption_categoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('exemption_category');
    }
}