<?php

/**
 * Faq
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    DemegaDropShip
 * @subpackage model
 * @author     Mrugendra Bhure
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class faq extends BaseFaq
{
    
}