<?php

/**
 * FaqTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class faqTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FaqTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('faq');
    }
    
    public function retrieveActive(Doctrine_Query $q)
    {
        $al = $q->getRootAlias();
        $q->addWhere($al.'.active = true');
        $q->orderBy($al.'.ordering');
        
        return $q;
    }
}