<?php

/**
 * formquestion_optionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class formquestion_optionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object formquestion_optionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('formquestion_option');
    }
}