<?php

/**
 * form_questionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class form_questionTable extends questionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object form_questionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('form_question');
    }
}