<?php

/**
 * itr_propertyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class itr_propertyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object itr_propertyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('itr_property');
    }
}