<?php

/**
 * itr_fileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class itr_fileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object itr_fileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('itr_file');
    }
}