<?php

/**
 * itr_other_incomeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class itr_other_incomeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object itr_other_incomeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('itr_other_income');
    }
}