<?php

/**
 * itr_securitiesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class itr_securitiesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object itr_securitiesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('itr_securities');
    }
}