<?php

/**
 * itr_exemptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class itr_exemptionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object itr_exemptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('itr_exemption');
    }
}