<?php

/**
 * itr_submissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class itr_submissionTable extends Doctrine_Table
{
    const AC_TYPE_SAVINGS = 1;
    const AC_TYPE_CURRENT = 2;
    const AC_TYPE_OTHER = 3;
    const AC_TYPE_NRO = 4;
    /**
     * Returns an instance of this class.
     *
     * @return object itr_submissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('itr_submission');
    }
}