<?php

/**
 * itr_submission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class itr_submission extends Baseitr_submission
{
    public function getStatusName()
    {
        $choices = array(            
            ""=>"Pending",
            "1"=>"Processing",
            "2"=>"Awaiting Customer Reply",
            "3"=>"Filed"
                );
        
        if( ($status = $this->getStatus()) )
        {
            return $choices[$status];
        }
        else
            return "Pending";
    }
}