<?php

/**
 * member_typeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class member_typeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object member_typeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('member_type');
    }
}