<?php

/**
 * member_subscriptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class member_subscriptionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object member_subscriptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('member_subscription');
    }
}