<?php

/**
 * member_couponTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class member_couponTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object member_couponTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('member_coupon');
    }
    
    public static function generateNewCode()
    {
        $chars = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        $is_duplicate = true;
        
        $duplicate_query = self::getInstance()
                            ->createQuery('mc')
                            ->addWhere('mc.coupon_code = ?');
        
        while($is_duplicate)
        {
            $res = "";            
            for ($i = 0; $i < 10; $i++) 
            {
                $res .= $chars[mt_rand(0, strlen($chars)-1)];
            }
            
            $is_duplicate = ($duplicate_query->count(array($res)) > 0);
        }
        
        return $res;
    }
}