<?php

/**
 * member_relationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class member_relationTable extends Doctrine_Table
{
    const RELATION_TYPE_SPOUCE = 'SP';
    const RELATION_TYPE_SIBLING = 'SB';
    const RELATION_TYPE_PARENT = 'P';
    const RELATION_TYPE_GRANDPARENT = 'GP';
    
    /**
     * Returns an instance of this class.
     *
     * @return object member_relationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('member_relation');
    }
    
    /**
     * Returns whether two members are related.
     * @param int $member_id1
     * @param int $member_id2
     * @return boolean
     */
    public static function areRelated($member_id1, $member_id2)
    {
        return  (self::getInstance()
                ->createQuery()
                ->addWhere('(member1 = ? AND member2 = ?) or (member1 = ? AND member2 = ?)', array($member_id1, $member_id2,$member_id2,$member_id1) )
                ->count() > 0);
    }
}