<?php

/**
 * newsneventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class newsneventTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object newsneventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('newsnevent');
    }
}