<?php

/**
 * order_itemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class order_itemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object order_itemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('order_item');
    }
}