<?php

/**
 * pan_applicationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class pan_applicationTable extends submissionTable
{
    const STATUS_TYPE_PAYMENT_PENDING  = 1;
    const STATUS_TYPE_PENDING  = 2;
    const STATUS_TYPE_PROCESSING = 3;
    const STATUS_TYPE_PROCESSED = 4;
    const STATUS_TYPE_AWAITING = 5;
    const STATUS_TYPE_REJECTED = 6;
    
    public static $STATUS_TYPES = array(
        "" => '--select--',
        SELF::STATUS_TYPE_PAYMENT_PENDING => 'Payment Pending',
        SELF::STATUS_TYPE_PENDING => 'Pending',
        SELF::STATUS_TYPE_PROCESSING => 'Processing',
        SELF::STATUS_TYPE_PROCESSED => 'Processed',
        SELF::STATUS_TYPE_AWAITING => 'Awaiting Detail',
        SELF::STATUS_TYPE_REJECTED => 'Rejected');
    /**
     * Returns an instance of this class.
     *
     * @return object pan_applicationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('pan_application');
    }
}