<?php

/**
 * pan_application
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class pan_application extends Basepan_application
{
  public function getStatuss() {
    $s = $this->getStatus();
    $arr = pan_applicationTable::$STATUS_TYPES;
    return $arr[$s];
  }
}