<?php

/**
 * product_usageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class product_usageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object product_usageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('product_usage');
    }
}