<?php

/**
 * productTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class productTable extends Doctrine_Table
{
    const CATEGORY_IT_RETURNS = 4;
    const CATEGORY_PAN_APPLICATION = 5;
    
    /**
     * Returns an instance of this class.
     *
     * @return object productTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('product');
    }
}