<?php

/**
 * product_category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class product_category extends Baseproduct_category
{
    public function __toString()
    {
        $catname = $this->getTypeName();
        if($catname)
        {
            return $catname;
        }
        else
            return "";
    }
}