<?php

/**
 * question_optionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class question_optionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object question_optionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('question_option');
    }
}