<?php

/**
 * settingsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class settingsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object settingsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('settings');
    }
    
    /** 
    * Performs the get Value in settings table
    * 
    * first check the record exists then get value
    * 
    * @param varchar settings_key
    */
    public static function getValue($settings_key)
    {
      $value = "";
      /* @var $settings settings */
      $settings = self::getInstance()->find($settings_key);
      if($settings)
        $value = $settings->getValue1();
      return $value;
    }
}