<?php

/**
 * site_pageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class site_pageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object site_pageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('site_page');
    }
}