<?php

/**
 * submission_inner_dataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class submission_inner_dataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object submission_inner_dataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('submission_inner_data');
    }
}