<?php

/**
 * submission_innerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class submission_innerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object submission_innerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('submission_inner');
    }
}