<?php

/**
 * submission_dataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class submission_dataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object submission_dataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('submission_data');
    }   
    
    public static function findBySubmissionIdAndQuestionIds($submission_id, $qids)
    {
        return self::getInstance()
               ->createQuery('sd')
               ->addWhere('sd.submission_id = ?', $submission_id)
               ->whereIn('sd.question_id', $qids)
               ->execute();
    }
}