<?php

/**
 * submissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class submissionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object submissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('submission');
    }
}