<?php

/**
 * submission_form
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class submission_form extends Basesubmission_form
{
    public function __toString() {
        if($this->getFormName())
            return $this->getFormName ();
        
        return "";
    }
}