<?php

/**
 * submission_formTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class submission_formTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object submission_formTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('submission_form');
    }
}