<?php

/**
 * subscription
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class subscription extends Basesubscription
{
    public function getITRProductId()
    {
        $itr_product = productTable::getInstance()
                    ->createQuery('p')
                    ->innerJoin('p.subscription_product sp')
                    ->addWhere('sp.subscription_id= ?', $this->getId())
                    ->addWhere('p.category_id = ?', product_categoryTable::CATEGORY_ITR )
                    ->fetchOne();
                
        return $itr_product->getId();
    }
}