<?php

/**
 * subscription_productTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class subscription_productTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object subscription_productTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('subscription_product');
    }
}