<?php

/**
 * subscriptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class subscriptionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object subscriptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('subscription');
    }
    
    /**
     * Returns active subscriptions
     * @return Doctrine_Collection
     */
    public function getActiveSubscriptions()
    {
        return $this->createQuery('ss')
              ->addWhere('ss.disabled is NULL or ss.disabled = 0')
              ->orderBy('ss.price asc')
              ->execute();
    }
}