<?php

/**
 * support_ticket
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    BestBuddies
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class support_ticket extends Basesupport_ticket
{
    public function getStatusName()
    {
        return support_ticketForm::$ticket_states[$this->getStatus()];
    }
    
    public function setUp() {
        parent::setUp();
        $this->hasMany('ticket_comment', array(
             'local' => 'id',
             'foreign' => 'ticket_id'));
        $this->addListener(new support_ticket_listener());
    }
    
     public function getReplyReceived(){
      $id = $this->getId();
      $query = Doctrine_Query::create()
          ->from('ticket_comment ')
          ->where('ticket_id = ?',$id)
          ->andWhere('is_reply = 1')
          ->count();
      if($query > 0)
        return "Yes";
      else
        return "No";
    }
    
    public function getNoOfComment(){
      $id = $this->getId();
      $query = Doctrine_Query::create()
          ->from('ticket_comment ')
          ->where('ticket_id = ?',$id)
          ->andWhere('is_reply = 1')
          ->count();
      if($query > 0)
        return $query;
      else
        return "";
    }
}