<?php

/**
 * ticket_commentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ticket_commentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ticket_commentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ticket_comment');
    }
}