<?php

/**
 * ticket_fileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ticket_fileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ticket_fileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ticket_file');
    }
}