<?php

/**
 * type_infoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class type_infoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object type_infoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('type_info');
    }
}