# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    
    - main.css
    - media.css
    - menu.css
    - ui-lightness/jquery-ui-1.10.0.custom.min.css
    - http://fonts.googleapis.com/css?family=Open+Sans+Condensed:700,300,300italic    
    - jmpress.min.js

  javascripts:    [jquery-1.9.0.min.js, jquery-ui-1.10.0.custom/js/jquery-ui-1.10.0.custom.min.js, jmpress.min.js ]

  has_layout:     true
  layout:         layout
