<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
    const OCCUPATION_TYPE_UNKNOWN = "";
    const OCCUPATION_TYPE_SALARY = 1;
    const OCCUPATION_TYPE_BUSINESS = 2;
    const OCCUPATION_TYPE_SALARY_N_BUSINESS = 3;
    
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUser');
    }
}