generator:
  class: sfDoctrineGenerator
  param:
    model_class:           faq
    theme:                 jRoller #admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          faq
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: "Frequently Asked Questions"
        object_actions:
          _edit:         ~
          _delete:       ~
        display: [question, answer, active, ordering]
        sort: [ordering, ASC]        
      filter:  
        display: [question, active, ordering]
      form:    
        fields:
          question:
            attributes: { size: 100 }          
      edit:    
      new:     ~
