generator:
  class: sfDoctrineGenerator
  param:
    model_class:           blog
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          blog
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
          title: Blogs
          display: [ title, _author, alert_on_comment, _approved, created_at, updated_at ]
          object_actions:
            _delete: ~
            show: 
              label:  Show
              action: show
            send_as_newsletter: 
              label:  Send As Newsletter
              action: sendAsNewsletter
              params:
                onclick: "sendAsNewsletter(this.href); return false;"
                #popup: 'width=500 height=400 scrollbars=0'
      filter:  
        display: [ title, author_id, approved, created_at, updated_at] 
      form:    
          fields:
              title:
                  attributes: 
                      size: 60
          display:
            Summary: [ title, status, alert_on_comment, approved ]
            Blog:  [ image, summary, blog  ]
          
      edit:    ~
      new:     ~
