## YAML Template.
#indexSuccess:
  #javascripts: 
  #  - -jquery-1.9.0.min.js
  #  - -jquery-ui-1.10.0.custom/js/jquery-ui-1.10.0.custom.min.js
editSuccess:
  javascripts: [ tinymce/tiny_mce_src.js ]
newSuccess:  
  javascripts: [ tinymce/tiny_mce_src.js ]    
  
listSuccess:
  javascripts: 
    - -jquery-1.9.0.min.js
    - -jquery-ui-1.10.0.custom/js/jquery-ui-1.10.0.custom.min.js

