generator:
  class: sfDoctrineGenerator
  param:
    model_class:           submission
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          submission
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        fields:
          submission_form: { label: Form }
          sfGuardUser: { label: Username }
        display: [id, submission_form, sfGuardUser, ip_address, archieved, created_at, updated_at] 
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
