generator:
  class: sfDoctrineGenerator
  param:
    model_class:           submission
    theme:                 jroller #admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          submission
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        fields:
          created_at: 
              date_format: dd/MM/y
          updated_at:
              date_format: dd/MM/y
          submission_form: { label: Form }
          sfGuardUser: { label: Username }
        display: [id, submission_form, sfGuardUser, ip_address, archieved, created_at, updated_at] 
        actions: []            
        sort: [created_at, desc]
      filter:  ~
      form:   ~          
      edit:    ~
      new:     ~
