# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/08-Security

default:
  is_secure: true
paymentVerified:
  is_secure: false
paymentConfirmed:
  is_secure: false
paymentnotification:
  is_secure: false
