## YAML Template.
all:      
  default_timezone: ~
  .actions:
    login_module:    sfGuardAuth
    login_action:    signin

    secure_module:          sfGuardAuth
    secure_action:          secure

