<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/10/09 12:04:13
sfConfig::add(array(
  'app_blog_alert_email_subject' => 'Best buddies blog: new comment received',
  'app_blog_alert_reply_email_subject' => 'Best buddies blog: you have received comment reply',
));
