<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/10/09 12:04:13

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=itservices',
  'username' => 'root',
  'password' => 'admin',
  'attributes' => 
  array (
    'tblname_format' => 'gts_%s',
  ),
  'name' => 'doctrine',
)),);
