<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/10/07 12:19:45
sfConfig::add(array(
  'mod_sfguardregister_enabled' => true,
  'mod_sfguardregister_view_class' => 'sfPHP',
));
