## YAML Template.
indexSuccess:
  layout: layout_home
  stylesheets:  
    
  javascripts:   
    - jquery.jmslideshow.js
    - modernizr.custom.48780.js
contactSuccess:
  layout: layout
  stylesheets: [ contact_form.css ]
      