cart_index:
  url:   /cart
  param: { module: cart, action: index }

cart_add:
  url:   /cart/add/:id
  param: { module: cart, action: add }
  
product_show:
  url:   /product/show/:id
  param: { module: product, action: show }
  
product_index:
  url:   /product/:page
  param: { module: product, action: index }

supportticket_sendreply:
  url:      /ticket/sendReply/:id
  param:    { module: ticket, action: sendReply }

support_ticket:
  class: sfDoctrineRouteCollection
  options:
    model:                support_ticket
    module:               ticket
    prefix_path:          /ticket
    column:               id
    with_wildcard_routes: true
    
panapplication_paymentVerified:
  url:      /panapplication/paymentVerified/:verify
  param:    { module: panapplication, action: paymentVerified }

submission:
  class: sfDoctrineRouteCollection
  options:
    model:                submission
    module:               submission
    prefix_path:          /submission
    column:               id
    with_wildcard_routes: true

member:
  class: sfDoctrineRouteCollection
  options:
    model:                member
    module:               profile
    prefix_path:          /profile
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
